{
 "title": "MySQL Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"mysqld-exporter\"})"
    }
   ]
  },
  {
   "title": "Queries per second (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "(irate(mysql_global_status_questions[30s]) or vector(0))"
    }
   ]
  },
  {
   "title": "Threads Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_connections"
    }
   ]
  },
  {
   "title": "Slow Queries (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[5m])"
    }
   ]
  },
  {
   "title": "Host CPU (node-exporter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(1 - (rate(mysql_global_status_innodb_buffer_pool_reads[5m]) / rate(mysql_global_status_innodb_buffer_pool_read_requests[5m]))) * 100"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(rate(mysql_global_status_bytes_sent[1m]) or vector(0))"
    },
    {
     "expr": "(rate(mysql_global_status_bytes_received[1m]) or vector(0))"
    }
   ]
  },
  {
   "title": "MySQL Commands (SELECT / INSERT / UPDATE per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "(rate(mysql_global_status_commands_total{command=\"select\"}[1m]) or vector(0))"
    },
    {
     "expr": "(rate(mysql_global_status_commands_total{command=\"insert\"}[1m]) or vector(0))"
    },
    {
     "expr": "(rate(mysql_global_status_commands_total{command=\"update\"}[1m]) or vector(0))"
    }
   ]
  }
 ]
}